"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_schema_1 = require("./auth.schema");
var auth_controller_1 = require("./auth.controller");
var joiValidator_1 = require("../../utils/joiValidator");
var authRoute = express_1.default.Router();
var authController = new auth_controller_1.default();
var joiValidator = new joiValidator_1.default();
authRoute.post("/create-user", joiValidator.validate(auth_schema_1.createUserBodyValidator, "body"), authController.createUser);
exports.default = authRoute;
