import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/helpers/redux/providers";
import SubApp from "@/components/SubApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Social Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-background text-foreground dark", inter.className)}>
        <Providers>
          <SubApp />
          {children}
        </Providers>
      </body>
    </html>
  );
}
